name: Deploy Angular App to AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.1'  # Specify the Node.js version you need
        
    - name: Install Angular CLI
      run: npm install -g @angular/cli@16.2.14

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: ng build --configuration=production

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist/Docker-Flow/ ec2-user@YOUR_EC2_IP:/Nemko_V3_Test/
